# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3t6MPMDN_X1qE8-Iuyo_Rj3waM7CQcW
"""

def get_radius(prompt):
  r = int(input(prompt))
  return r

R = get_radius("넓이를 구하고자 하는 원의 반지름은? ")
def get_circle_area():
  area = R * R * 3.14
  return print("반지름이 %d인 원의 넓이 = 3.14 x %d x %d = %.02f" %(R, R, R, area))
get_circle_area()

