# -*- coding: utf-8 -*-
"""hw10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LiOYNtTOmsgx3KybObWNLJRFmV6Pd6Mu

## 풀이 코드
"""

import pickle

def save_scores(scores):
    """주어진 점수 리스트를 파일에 저장한다."""
    with open('data/score.bin', 'wb') as f:
        pickle.dump(scores, f)

def load_scores():
    """파일에서 점수 리스트를 로드한다."""
    with open('data/score.bin', 'rb') as f:
        scores = pickle.load(f)
    return scores

def input_scores():
    """사용자로부터 성적을 입력받아 리스트로 반환한다."""
    scores = []
    while True:
        score = int(input("점수 입력 (#종료 -1): "))
        if score == -1:
            break
        scores.append(score)
    return scores

def calculate_statistics(scores):
    """점수 리스트로부터 최고 점수와 평균 점수를 계산하여 반환한다."""
    if not scores:
        return None, None
    max_score = max(scores)
    average_score = sum(scores) / len(scores)
    return max_score, average_score

def main():
    scores = input_scores()
    save_scores(scores)
    loaded_scores = load_scores()
    max_score, average_score = calculate_statistics(loaded_scores)
    print(f'최고 점수: {max_score}')
    print(f'평균 점수: {average_score:.1f}')

if __name__ == '__main__':
    main()

"""## 참고코드"""

lst = []
def input_scores():
  i = 1
  score = 0
  print('[점수 입력]')
  while(score >= 0):
    score = int(input(f'#{i}? '))
    i += 1
    if(score >= 0):
      lst.append(score)

  return lst

def get_average(lst):
  ave = sum(lst)/len(lst)
  return ave

def show_scores(lst):
  for i in range(len(lst)):
    print(f'개인점수: {lst[i]}')

lst = input_scores()
average = get_average(lst)
print('[점수 출력]')
show_scores(lst)
print(f'평균: {average}')