# -*- coding: utf-8 -*-
"""hw5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uW7DTN8KX51e3l8gw7d9HId1pixMuTXn
"""

def read_number(s):
  if(s >= 100) and (s <= 999):
    num = str(s)
    num1 = num[0]
    num2 = num[1]
    num3 = num[2]

    nnum1 = int(num1)
    nnum2 = int(num2)
    nnum3 = int(num3)

    c1 = read_single_digit(nnum1)
    c2 = read_single_digit(nnum2)
    c3 = read_single_digit(nnum3)

    return c1, c2, c3


  elif(s >= 10) and (s <= 99):
    num = str(s)
    num1 = num[0]
    num2 = num[1]

    nnum1 = int(num1)
    nnum2 = int(num2)

    c1 = read_single_digit(nnum1)
    c2 = read_single_digit(nnum2)

    return c1, c2

  elif(s >= 0 )and (s <= 9):

    c1 = read_single_digit(s)

    return c1

def read_single_digit(s):
  if(s == 1):
    r = '일'
  elif(s == 2):
    r = '이'
  elif(s == 3):
    r = '삼'
  elif(s == 4):
    r = '사'
  elif(s == 5):
    r = '오'
  elif(s == 6):
    r = '육'
  elif(s == 7):
    r = '칠'
  elif(s == 8):
    r = '팔'
  elif(s == 9):
    r = '구'

  return r


number = int(input('세 자리 정수 입력: '))
if(number >= 100) and (number <= 999):
  char1, char2, char3 = read_number(number)
  print(f'{char1} {char2} {char3}')
elif(number >= 10) and (number <= 99):
  char1, char2 = read_number(number)
  print(f'{char1} {char2}')
elif(number > 0) and (number < 10):
  char = read_number(number)
  print(char)

