# -*- coding: utf-8 -*-
"""hw8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bevy4M7re5NZnBat_INJ-3Y7sp2_mxIP
"""

shopping_bag = {}
def buy(dic):
  name = input('상품명은? ')

  if(name == ''):
    return False
  num = int(input('수량은? '))
  dic[name] = num
  return dic

def show(dic):
  print(dic)

def find(dic):
  name = input('장바구니에서 확인하고자 하는 상품은? ')
  if name in dic:
    print(f'{name}(는) {dic[name]}개 담겨 있습니다.')
  else:
    print(f'장바구니에 {name}은(는) 없습니다.')

while True:
  if buy(shopping_bag) == False:
    break

show(shopping_bag)
find(shopping_bag)