# -*- coding: utf-8 -*-
"""hw9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtWtGVzrGacSGzy7RbXnxebXWxGz-EBw
"""

class Rectangle:
  def __init__(self, x1,y1,x2,y2):
    self.__x1 = x1
    self.__y1 = y1
    self.__x2 = x2
    self.__y2 = y2

  def show(self):
    print(f'left-top의 꼭지점은 ({self.__x1}, {self.__y1}) 이고 right-bottom의 꼭지점은 ({self.__x2}, {self.__y2}) 입니다.')

  def getWidth(self):
    return self.__x2 - self.__x1

  def getHeight(self):
    return self.__y1 - self.__y2

  def getArea(self):
    return (self.__x2 - self.__x1) * (self.__y2 - self.__y1)

  def getPerimeter(self):
    return ((self.__x2 - self.__x1) + (self.__y2 - self.__y1))*2


class Point:
  def __init__(self, x ,y):
    self.__x = x
    self.__y = y

r1 = Rectangle(5,5,20,10)
a = r1.getArea()
p = r1.getPerimeter()

r1.show()
print(f'\n넓이는 {a}, 둘레는 {p}')